import type { WalletCard } from "./types";

export const demoWallet: WalletCard[] = [
  {
    id: "icici",
    name: "ICICI Platinum",
    issuer: "ICICI Bank",
    network: "Visa",
    accent: "#192f6a",
    lastFour: "4821",
    statementDay: 18,
    dueDay: 7,
    rules: [
      {
        id: "icici-dining",
        label: "Dining rewards",
        rate: 2.5,
        cap: 500,
        capPeriod: "monthly",
        used: 120,
        categories: ["dining"],
        confidence: "high",
        source: "Saved issuer terms",
        checkedAt: "12 min ago",
        isDemo: true,
      },
      {
        id: "icici-base",
        label: "Base rewards",
        rate: 0.75,
        confidence: "medium",
        source: "Saved issuer terms",
        checkedAt: "12 min ago",
        isDemo: true,
      },
    ],
  },
  {
    id: "kotak",
    name: "Kotak League",
    issuer: "Kotak Mahindra Bank",
    network: "Visa",
    accent: "#5a2037",
    lastFour: "8134",
    statementDay: 2,
    dueDay: 22,
    rules: [
      {
        id: "kotak-dining",
        label: "Dining cashback",
        rate: 4,
        cap: 400,
        capPeriod: "monthly",
        used: 40,
        categories: ["dining"],
        confidence: "high",
        source: "Saved issuer terms",
        checkedAt: "28 min ago",
        isDemo: true,
      },
      {
        id: "kotak-base",
        label: "Base rewards",
        rate: 0.5,
        confidence: "medium",
        source: "Saved issuer terms",
        checkedAt: "28 min ago",
        isDemo: true,
      },
    ],
  },
  {
    id: "axis",
    name: "Axis Neo",
    issuer: "Axis Bank",
    network: "Visa",
    accent: "#443278",
    lastFour: "0209",
    statementDay: 12,
    dueDay: 1,
    rules: [
      {
        id: "axis-dining",
        label: "Dining reward",
        rate: 3,
        cap: 250,
        capPeriod: "monthly",
        used: 0,
        categories: ["dining"],
        confidence: "medium",
        source: "Example evidence record",
        checkedAt: "2 days ago",
        isDemo: true,
      },
      {
        id: "axis-base",
        label: "Base rewards",
        rate: 1,
        confidence: "medium",
        source: "Example evidence record",
        checkedAt: "2 days ago",
        isDemo: true,
      },
    ],
  },
];
